site:
  title: "QuickStart Manual"
  url: https://localhost/
  start_page: en@manuals:ROOT:index.adoc

urls:
  html_extension_style: indexify
asciidoc:
  attributes:
    icons: font
antora:
  extensions:
    languages: [en, fr]
content:
  edit_url: true
  sources:
  - url: https://github.com/opencpn-manuals/quickstart-docs.git
    start_paths:
      - fr
      - en
      
    branches:
      - main
ui:
  bundle:
    url: ./ui-bundle.zip
    #snapshot: true
    #url: ../antora-ui-default/build/ui-bundle.zip
    #supplemental_files: ./node_modules/@antora/lunr-extension/supplemental_ui
  supplemental_files: ./supplemental_ui
output:
  dir: ./public

